- name: Config Active directory
  hosts: all
  tasks: 

  - name: Run powershell commands to prepare the DC 
    ansible.windows.win_powershell:
      script: |
- name: Configure role(s) on a Windows server instance
  hosts: all
  tasks: 

  - name: Run powershell commands to add AD-DS
    ansible.windows.win_powershell:
      script: | 
        Add-WindowsFeature AD-Domain-Services
        Set-TimeZone -Name "Romance Standard Time"

  - name: Change the hostname 
    ansible.windows.win_hostname:
      name: DC-01
    register: hostname
  
  - name: Reboot
    ansible.windows.win_reboot:
    when: hostname.reboot_required

  - name: Install ADDS role and configure it with minimal option
    ansible.windows.win_domain:
      dns_domain_name: poc.local
      safe_mode_password: password123!
    register: domain_install
  
  - name: Reboot after promotion
    ansible.windows.win_reboot:
    when: domain_install.reboot_required
    
- name: Add user on domain
  hosts: DC-01
  tasks:
    - name: Ajouter l'utilisateur "law" au domaine
      win_domain_user:
        domain_username: "administrator"  # Nom d'utilisateur avec les privilèges pour ajouter des utilisateurs
        domain_password: "vagrant"  # Mot de passe de l'utilisateur avec les privilèges pour ajouter des utilisateurs
        name: "law"  # Nom de l'utilisateur à ajouter
        password: "azerty123!"  # Mot de passe de l'utilisateur à créer
        state: present  # Pour s'assurer que l'utilisateur existe
        domain: "poc.local"  # Nom de domaine

