# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server-2022-standard"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.hostname = "test-windows"
  config.vm.provider "virtualbox" do |hv|
    hv.cpus = 2
    hv.memory = 4096
  end

  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provision-playbook.yml"
  end
end
