- name: Config Active directory
  hosts: all
  tasks: 

  - name: Run powershell commands to prepare the DC 
    ansible.windows.win_powershell:
      script: |
        # Your PowerShell script here

- name: Configure role(s) on a Windows server instance
  hosts: all
  tasks: 

  - name: Modification du clavier en français
    ansible.windows.win_powershell:
      script: |
        Set-WinUserLanguageList fr-FR -Force

  - name: Ajout du rôle AD-DS
    ansible.windows.win_powershell:
      script: | 
        Add-WindowsFeature AD-Domain-Services
        Set-TimeZone -Name "Romance Standard Time"

  - name: Ajout du nom d'hôte 
    ansible.windows.win_hostname:
      name: DC-01
    register: hostname
  
  - name: Reboot
    ansible.windows.win_reboot:
    when: hostname.reboot_required

  - name: Installation du domaine
    ansible.windows.win_domain:
      dns_domain_name: poc.local
      safe_mode_password: Vagrant!2024
    register: domain_install
  
  - name: Reboot after promotion
    ansible.windows.win_reboot:
    when: domain_install.reboot_required

  - name: Création du goupe PocAdmin
    ansible.windows.win_group:
      name: PocAdmin
      description: PocAdmin Users
      state: present

  - name: Création du goupe PocUtilisateur
    ansible.windows.win_group:
      name: PocUsers
      description: Poc users
      state: present

- name: Ajout des utilisateurs au domaine
  hosts: all
  tasks:
    - name: Ajouter l'utilisateur "law" au domaine
      win_domain_user:
        domain_username: "administrator"
        domain_password: "vagrant"
        name: "law"
        password: "azerty123!"
        state: present 
        domain_server: "poc.local"
    - name: Ajout de l'utilisateur "travis" au domaine
      win_domain_user:
        name: "travis"
        password: "3CAn5F@2024"
        state: present
        domain_server: "poc.local"
    - name: Ajout de l'utilisateur "tyson" au domaine
      win_domain_user:
        name: "tyson"
        password: "M&UYNr2024!"
        state: present
        domain_server: "poc.local"
    - name: Add users to PocUsers group
      win_shell: |
        Add-ADGroupMember -Identity "PocUsers" -Members "travis"
        Add-ADGroupMember -Identity "PocUsers" -Members "tyson"
        Add-ADGroupMember -Identity "PocAdmin" -Members "law"
                 

