# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.network "private_network", ip: "192.168.56.13"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "6024"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    powershell -Command "Set-WinUserLanguageList -LanguageList fr-FR -Force"
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
