- name: Config Active directory
  hosts: all
  tasks: 

  - name: Run powershell commands to prepare the DC 
    ansible.windows.win_powershell:
      script: |
- name: Configure role(s) on a Windows server instance
  hosts: all
  tasks: 

  - name: Modification du clavier en français
    ansible.windows.win_powershell:
      script: |
        Set-WinUserLanguageList fr-FR -Force

  - name: Ajout du rôle AD-DS
    ansible.windows.win_powershell:
      script: | 
        Add-WindowsFeature AD-Domain-Services
        Set-TimeZone -Name "Romance Standard Time"

  - name: Ajout du nom d'hôte 
    ansible.windows.win_hostname:
      name: DC-01
    register: hostname
  
  - name: Reboot
    ansible.windows.win_reboot:
    when: hostname.reboot_required

  - name: Installation du domaine
    ansible.windows.win_domain:
      dns_domain_name: poc.local
      safe_mode_password: Vagrant!2024
    register: domain_install
  
  - name: Reboot after promotion
    ansible.windows.win_reboot:
    when: domain_install.reboot_required
    
- name: Add user on domain
  hosts: all
  tasks:
    - name: Ajouter l'utilisateur "law" au domaine
      win_domain_user:
        domain_username: "administrator"
        domain_password: "vagrant"
        name: "law"
        password: "azerty123!"
        state: present 
        domain: "poc.local"
    - name: Add user to Domain Admins group
      win_shell: Add-ADGroupMember -Identity "Domain Admins" -Members "law"
      

