# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Windows_Server" do |windows|
    windows.vm.box = "Vagrant_Project_M2I/Windows_Serveur"
    windows.vm.network "private_network", ip: "192.168.56.11"
end

config.vm.provision "shell", inline: <<-SHELL

  SHELL
end