# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "DC-01" do |ad|
    #ad.vm.box = "Vagrant_Project_M2I/Windows_Serveur"
    #ad.vm.network "private_network", ip: "192.168.56.11"
    ad.vm.box = "gusztavvargadr/windows-server-2022-standard"
    #ad.vm.box = "peru/windows-server-2019-standard-x64-eval"
    
  end
  
  config.vm.provider "virtualbox" do |hw|
    hw.cpus = 4
    hw.memory = "4096"
    hw.name = "DC-01"
  end
  
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-ansible.yml"
  end  

end


