# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Kali_Vagrant" do |kali|
    kali.vm.box = "Vagrant_Project_M2I/Kali"
    kali.vm.network "private_network", ip: "192.168.56.12"
    kali.vm.network "forwarded_port", guest: 21, host: 1234

    kali.vm.provider "virtualbox" do |vb|
      vb.name = "Kali_Vagrant"
    end
  end
end