# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Vagrant_Project_M2I/Kali"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.provision "shell", inline: <<-SHELL
    # Installation des prérequis
    apt-get update
    apt-get upgrade -y
    # Ajout payload GLPI 
    cd /home/vagrant/Documents
    git clone https://github.com/cosad3s/CVE-2022-35914-poc.git
    cd CVE-2022-35914-poc
    pip install -r requirements.txt
  SHELL
end
