# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "Ubuntu_Server" do |ubuntu|
    ubuntu.vm.box = "Vagrant_Project_M2I/Linux"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.network "forwarded_port", guest: 21, host: 2121
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    end
  end
  
  config.vm.provision "shell", inline: <<-SHELL
  # Installation des prérequis
    apt-get update
    apt-get upgrade -y
    apt-get install -y apache2 mariadb-server php libapache2-mod-php php-mysql
    # Configuration de la base de donées GLPI
    mysql -u root -e "CREATE DATABASE glpi;"
    mysql -u root -e "CREATE USER 'glpi'@'localhost' IDENTIFIED BY 'password';"
    mysql -u root -e "GRANT ALL PRIVILEGES ON glpi.* TO 'glpi'@'localhost';"
    mysql -u root -e "FLUSH PRIVILEGES;"
    # Télécharement de GLPI
    wget https://github.com/glpi-project/glpi/releases/download/9.5.5/glpi-9.5.5.tgz
    tar -xvzf glpi-9.5.5.tgz -C /var/www/html/
    chown -R www-data:www-data /var/www/html/glpi
    chmod -R 755 /var/www/html/glpi
    # Configuration d'apache
    echo "<VirtualHost *:80>
        DocumentRoot /var/www/html/glpi
        <Directory /var/www/html/glpi>
            AllowOverride All
            Require all granted
        </Directory>
    </VirtualHost>" > /etc/apache2/sites-available/glpi.conf
    a2ensite glpi.conf
    a2dissite 000-default.conf
    service apache2 restart
    # Installation de proftpd
    wget ftp://ftp.proftpd.org/distrib/source/proftpd-1.3.5.tar.gz
    tar xfz proftpd-1.3.5.tar.gz
    cd proftpd-1.3.5
    sudo ./configure --with-modules=mod_copy
    make && sudo make install
    sudo /usr/local/sbin/proftpd
    # Ajout du flag
    echo "NHM2I{glpi}" > /home/vagrant/.notes
  SHELL
end