# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.provider "virtualbox" do |v|
    v.name = "Serveur_DHCP"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install x11-xkb-utils -y
    echo 'XKBLAYOUT="fr"' >> /etc/default/keyboard
    dpkg-reconfigure keyboard-configuration
    service keyboard-setup restart
    useradd -p $(openssl passwd -1 'M2I') Memoire
  SHELL
end